// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ForcasrSummaryWebApi.MetaData
{
    public partial class budgetForecastContext : DbContext
    {
        public budgetForecastContext()
        {
        }

        public budgetForecastContext(DbContextOptions<budgetForecastContext> options)
            : base(options)
        {
        }

        public virtual DbSet<SummaryForcast> SummaryForcast { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SummaryForcast>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("summaryForcast");

                entity.Property(e => e.Brand).HasMaxLength(1000);

                entity.Property(e => e.Category).HasMaxLength(1000);

                entity.Property(e => e.CreatedDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Createdby)
                    .HasMaxLength(50)
                    .HasDefaultValueSql("('admin')");

                entity.Property(e => e.IsActive).HasDefaultValueSql("((1))");

                entity.Property(e => e.Period).HasColumnName("period");

                entity.Property(e => e.Source).HasMaxLength(1000);

                entity.Property(e => e.SubCategory).HasMaxLength(1000);

                entity.Property(e => e.SummaryForcastId)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("summaryForcastID");

                entity.Property(e => e.TtldollarSales)
                    .HasColumnType("money")
                    .HasColumnName("TTLDollarSales");

                entity.Property(e => e.UldollarSales)
                    .HasColumnType("money")
                    .HasColumnName("ULDollarSales");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(50)
                    .HasDefaultValueSql("('admin')");

                entity.Property(e => e.UpdatedDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Week)
                    .HasColumnType("date")
                    .HasColumnName("week");

                entity.Property(e => e.Year).HasColumnName("year");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}