// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ForcasrSummaryWebApi.MetaData;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ForcasrSummaryWebApi.MetaData
{
    public partial interface IbudgetForecastContextProcedures
    {
        Task<List<uploadDataResult>> uploadDataAsync(string jsonData, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_GetDimFactDataResult>> usp_GetDimFactDataAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
