// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ForcasrSummaryWebApi.MetaData;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ForcasrSummaryWebApi.MetaData
{
    public partial interface IbudgetForecastContextProcedures
    {
        Task<List<USP_GetSummaryDataResult>> USP_GetSummaryDataAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<USP_GetSummaryDataByBrandResult>> USP_GetSummaryDataByBrandAsync(string SubCatagoery, string source, string brands, string years, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
