// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ForcasrSummaryWebApi.MetaData
{
    public partial class Per9
    {
        public string Source { get; set; }
        public string Category { get; set; }
        public string Brand { get; set; }
        public string Year { get; set; }
        public string Subcategory { get; set; }
        public string SalesType { get; set; }
        public int? _1 { get; set; }
        public int? _2 { get; set; }
        public int? _3 { get; set; }
        public int? _4 { get; set; }
        public int? _5 { get; set; }
        public int? _6 { get; set; }
        public int? _7 { get; set; }
        public int? _8 { get; set; }
        public int? _9 { get; set; }
        public int? _10 { get; set; }
        public int? _11 { get; set; }
        public int? _12 { get; set; }
        public int? _13 { get; set; }
        public int SortOrder { get; set; }
    }
}